/**
 * generated by Xtext 2.40.0
 */
package su.nsk.iae.post.poST;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inline code</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.post.poST.Inline_code#getInline_code <em>Inline code</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getInline_code()
 * @model
 * @generated
 */
public interface Inline_code extends Statement
{
  /**
   * Returns the value of the '<em><b>Inline code</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inline code</em>' attribute list.
   * @see su.nsk.iae.post.poST.PoSTPackage#getInline_code_Inline_code()
   * @model unique="false"
   * @generated
   */
  EList<String> getInline_code();

} // Inline_code
